language: python

env:
  - LUA="lua 5.1"
  - LUA="lua 5.2"
  - LUA="lua 5.3"
  - LUA="lua 5.4"
  - LUA="luajit 2.0"
  - LUA="luajit 2.1"

before_install:
  - pip install hererocks
  - hererocks $HOME/env --$LUA -rlatest    # Use latest LuaRocks, install into 'env' directory.
  - source $HOME/env/bin/activate          # Add directory with all installed binaries to PATH.
  - luarocks install luacheck

script:
  - timeout 5 lua test/basic.lua
  - luacheck .
